### ISSUE TITLE
アンダーフローについて

### ISSUE THREAD

**Issue by dalance** [kaityo256/python_zero#2]
basic/README.md にあるアンダーフローバグですが、これは一般的には負のオーバーフローと呼ばれるものではないでしょうか？
「核ガンジー」ネタの説明としてなら正直どちらでもいいと思いますが、プログラミング初学者向けという文脈ならちょっと気になります。
これをアンダーフローと呼ぶ人もそれなりにいるのでいずれ市民権を得るかもしれませんが、現時点ではそこまで広まっておらず明確に間違いだと主張する人も結構いる、という状況かと思います。

**Comment by kaityo256** [comment]
@dalance さん

ありがとうございます。つい癖で整数の下側溢れを「アンダーフロー」と言ってしまうのですが、ご指摘の通り「オーバーフロー」が正しい用語だと思いますので、修正いたしました。

**Comment by dalance** [comment]
どういたしまして。
ちょっと不安になって調べてしまいましたが、どうも脆弱性界隈では
integer underflowと呼ぶことがあるようですかね。
ともあれ対応ありがとうございました。
