### ISSUE TITLE
possibly typo?

### ISSUE THREAD

**Issue by tueda** [kaityo256/python_zero#32]
非常に面白い講義ノートを公開していただきありがとうございます。いつも参考にさせていただいております。

本質的なことではなくて恐縮ですが、少し気になってしまったのでご報告させていただきます：
[数値シミュレーション](https://kaityo256.github.io/python_zero/simulation/index.html)の章の初めの方にある「極限すれば」はもしかして「極言すれば」、もしくは「極論すれば」のタイプミスだったりしないでしょうか？

https://github.com/kaityo256/python_zero/blame/72519ced963c29f70f8701c66be6ae7d3ff5e614/simulation/README.md#L12

（もし意図的な表現であったなら大変申し訳ありません。）

**Comment by kaityo256** [comment]
@tueda さん

ご指摘をありがとうございます。おっしゃる通り、タイポですね。次のコミットで修正しておきます。
