### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by iwaokimura** [kaityo256/python_zero#34]
[五芒星](https://github.com/kaityo256/python_zero/blob/main/hello/README.md#2-%E4%BA%94%E8%8A%92%E6%98%9F%E3%81%AE%E6%8F%8F%E7%94%BB) のプログラムリストの2行目 ```draw = ImageDraw.Draw(im)``` は  ```draw = ImageDraw.Draw(img)``` だと思います。

**Comment by kaityo256** [comment]
@iwaokimura さん
ご指摘ありがとうございます。おっしゃる通り、typoですね。修正しておきました。
