### ISSUE TITLE
typo in fig

### ISSUE THREAD

**Issue by iwaokimura** [kaityo256/python_zero#37]
8章「クラストオブジェクト指向」の[図](https://github.com/kaityo256/python_zero/blob/6ce158c9efd3d4a6ff380595f238acb0d5f3a23d/class/fig/class.png) （書籍版だとp. 124）の中のコードで，`self.num` となっているところはいずれも，`self.__num` でしょうか？

**Comment by kaityo256** [comment]
@iwaokimura さん、ご指摘ありがとうございます。おっしゃるとおり、`self.__num`の間違いですね。正誤表に追加し、ウェブ版は修正しておきます。
