### ISSUE TITLE
p.47, 49, 50の図

### ISSUE THREAD

**Issue by mkoeda** [kaityo256/python_zero#43]
図4.1　リストのメモリ上での表現，の右の図
a=[1]=4　→　a[1]=4
2　→　4

図4.3　リストのコピー，の右上の図
a=[1]=4　→　b[1]=4

図4.3　リストのコピー，の下の図
a=[1] # => 4　→　a[1] # => 4

図4.4　コピー後のリストの代入，の下の図
a=[4,5,6]　→　b=[4,5,6]

では無いでしょうか？

**Comment by kaityo256** [comment]
@mkoeda さん
ご指摘ありがとうございます。おっしゃる通り、全て誤植ですので、[正誤表](https://kaityo256.github.io/python_zero/errata/)に追加いたしました。次版で修正いたします。なお、図4.1で`a[1]=4`と代入しているのに、図のメモリの指す値が2のままなのは、`a[1]`の場所がここで、ここにこれから4が入るよ、という気持ちなので、2のままにしておきます。図4.3は代入済みの気持ちなのでメモリには4が記載されています。
